apiVersion: v1
data:
  admin-password: <REDACTED_PASSWORD_B64>
  admin-user: eGFsZw==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"admin-password":"<REDACTED_PASSWORD_B64>","admin-user":"eGFsZw=="},"kind":"Secret","metadata":{"annotations":{},"name":"grafana-admin-credentials","namespace":"monitoring"},"type":"Opaque"}
  creationTimestamp: "2025-05-21T15:19:16Z"
  name: grafana-admin-credentials
  namespace: monitoring
  resourceVersion: "310445"
  uid: c654ab0c-55d7-436f-9dec-be53d5e475cb
type: Opaque
