apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: ethosenv
spec:
  template:
    spec:
      containers:
      - name: wordpress
        resources:
          requests:
            cpu: "1000m"       # Conservative increase from 500m
            memory: "1Gi"   # Conservative increase from 256Mi
          limits:
            cpu: "1200m"      # Conservative increase from 1000m
            memory: "2Gi"     # Conservative increase from 512Mi
